package minetweaker;

import java.util.List;

/**
 * The class registry provides the list of annotated classes to the scripting
 * system.
 * 
 * @author Stan Hebben
 */
public class ClassRegistry {
	public static void getClasses(List<Class> output) {
		// method stub; contents generated by RegisterZenClassesTask
	    // TODO: Remove this temporary hack
	    output.add(minetweaker.api.item.IItemStack.class);
	    output.add(minetweaker.api.item.IIngredient.class);
	    output.add(minetweaker.api.data.IData.class);
	    output.add(minetweaker.expand.ExpandAnyDict.class);
        output.add(minetweaker.expand.ExpandString.class);
	}
}
